# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: "QTf$6SLGmzBFcQ535NsE!%Tx"

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: "t8wjV@EeY!zXnzA7?mC&=+m9"
    salt: "6K4f9@rmL4qYR-&bw4dfqRXM"

# Variables to accompany `group_vars/production/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  invizbox.com:
    env:
      db_password: "5bT+?jnnfkEq_SeWdAf3s24m"
      acf_pro_key: "b3JkZXJfaWQ9MzUzODh8dHlwZT1wZXJzb25hbHxkYXRlPTIwMTQtMDctMjEgMTU6MjY6Mzg="
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "4RHYORHH@9B5pC3g$!jwq2Oc}Z*_9v=Lufbr&4)J:*7V`O*%,.^wRi$5IAKr</c;"
      secure_auth_key: "Qb@`ZtW[zMs*tDv(jmUBs:%bhD=e&)mgQdJbm([$tzEW:7Gr2B>9NB::NmR-7cxP"
      logged_in_key: "K*%_0p&f]k8JC&AP_y.g@@eUJP*eL;+`!pQE@8z`@g_1_XQ4uBWsNEyBBClNujvF"
      nonce_key: "6hf3#j,1|`UU/X5wi350ax-c8[w.)ByyqBY0|(VebOD[&5k&;6RNa/i*tyC*B78S"
      auth_salt: "V_0n>`^]H(AabX(>`ku+_GySaU)8#%RgC09ghGx4GgoTtc=3sF6c};%IMS0UIk:}"
      secure_auth_salt: "zJ?u@g+Y(N$H+xA01Qb*Nd%$MUYG^`cI/[0/_w=,XsLRM*&Sml}gJN6=oZ1j{V]1"
      logged_in_salt: "]?M<=Wl|M<)7VK*EUW@KF[M$!FCvbLBmtDI{b$YNePu`.N]O6@J/9(r?$2[]BP3+"
      nonce_salt: ")tRp3S=C<lBf5?-Y.n0uFGSi.([}0VM4ak;R4}V-7pvJ;Bo}JGxzOm{^<8zq.CvM"
